name: 1 - [FEAT] Open PR

on:
  push:
    branches:
      - "feature**"

jobs:
  create_pr_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "feat: Feature para Develop"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_draft: true