name: 4 - [MAIN] Apply & Deploy

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"

jobs:
  terraform-apply-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Download Terraform Plan
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 3-pr-develop-to-main.yml
          path: ./infra
      - name: Terraform Init and Apply
        shell: bash
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve tfplan/tfplan